# _config.yml
title: Team Website
email: your-email@example.com
description: >-
  Team site.

url: "https://marcoschumacher-uniwuppertal.github.io"
baseurl: "/Team-Website"


#theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

author:
  name: "Marco Schumacher"
  avatar: "/assets/images/avatar.png"
  bio: "System admin."
  location: "Wuppertal, Germany"

#conetent management system

collections:
  news:
    output: true
    permalink: /news/:slug/

defaults:
  - scope:
      path: ""
      type: news
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
