# _config.yml
title: Osnabrück Vision AI Lab - OSVIA
description: "Research group at Osnabrück University focusing on computer vision and modern deep learning."
url: "https://osvia.org"
author: 
  name: "OSVIA Lab"
  email: "matthias.rottmann@uni-osnabrueck.de"
lang: "en"


#theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap

#conetent management system

collections:
  news:
    output: true
    permalink: /news/:slug/
  
  publications:
    output: true
    permalink: /publications/:slug/

  team:
    output: false

defaults:
  - scope:
      path: ""
      type: news
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
